"""Generate the Python API reference pages from the Python adapter's source.

Reads signatures and docstrings statically with griffe (no import, so the
compiled extension does not need to be built) and writes one Markdown page
per public module into the docs content tree. PyO3 turns Rust `///` comments
into docstrings, so for bound items these docs come from the Rust source.

Usage: python_api.py <search path> <package> <output dir>
"""

from __future__ import annotations

import re
import shutil
import sys
from pathlib import Path

import griffe

HEADING = re.compile(r"^(#{1,3})(\s)")


def main() -> None:
    search_path, package, out_dir = Path(sys.argv[1]), sys.argv[2], Path(sys.argv[3])

    root = griffe.load(
        package,
        search_paths=[search_path],
        docstring_parser=griffe.Parser.google,
        allow_inspection=False,
    )

    # The directory is fully generated, so rebuild it to drop deleted modules.
    shutil.rmtree(out_dir, ignore_errors=True)
    out_dir.mkdir(parents=True)

    for module in walk_modules(root):
        (out_dir / f"{module.path}.md").write_text(render_module(module))


def walk_modules(module: griffe.Module):
    yield module
    for member in module.modules.values():
        if is_public(member):
            yield from walk_modules(member)


def is_public(obj: griffe.Object | griffe.Alias) -> bool:
    return not obj.name.startswith("_") and not obj.is_alias


def members_of(obj: griffe.Object, kind: griffe.Kind) -> list[griffe.Object]:
    return [m for m in obj.members.values() if m.kind is kind and is_public(m)]


def render_module(module: griffe.Module) -> str:
    out = [
        "---",
        f"title: {module.path}",
        f"description: API reference for the {module.path} Python module.",
        "editUrl: false",
        "---",
        "",
        "<!-- Generated by docs/scripts/python_api.py. Do not edit. -->",
        "",
    ]
    out += render_docstring(module, level=2)

    for cls in members_of(module, griffe.Kind.CLASS):
        out += render_class(cls)

    functions = members_of(module, griffe.Kind.FUNCTION)
    if functions:
        out += ["## Functions", ""]
        for fn in functions:
            out += render_function(fn, level=3)

    attributes = members_of(module, griffe.Kind.ATTRIBUTE)
    if attributes:
        out += ["## Attributes", ""]
        for attr in attributes:
            out += render_attribute(attr, level=3)

    return "\n".join(out).rstrip() + "\n"


def render_class(cls: griffe.Class) -> list[str]:
    bases = f"({', '.join(str(b) for b in cls.bases)})" if cls.bases else ""
    out = [f"## `{cls.name}`", "", "```python", f"class {cls.name}{bases}", "```", ""]
    out += render_docstring(cls, level=3)

    init = cls.members.get("__init__")
    if init is not None and init.kind is griffe.Kind.FUNCTION:
        out += render_function(init, level=3, name=cls.name)

    for attr in members_of(cls, griffe.Kind.ATTRIBUTE):
        out += render_attribute(attr, level=3)
    for method in members_of(cls, griffe.Kind.FUNCTION):
        out += render_function(method, level=3)
    return out


def render_function(fn: griffe.Function, level: int, name: str | None = None) -> list[str]:
    params = format_parameters(fn)
    if name:
        # A constructor, shown the way it is called.
        signature = f"{name}({params})"
    else:
        name = fn.name
        prefix = "async def" if "async" in fn.labels else "def"
        returns = f" -> {fn.returns}" if fn.returns else ""
        signature = f"{prefix} {name}({params}){returns}"
    out = [f"{'#' * level} `{name}()`", ""]
    out += ["```python", signature, "```", ""]
    out += render_docstring(fn, level=level + 1)
    return out


def render_attribute(attr: griffe.Attribute, level: int) -> list[str]:
    annotation = f": {attr.annotation}" if attr.annotation else ""
    out = [f"{'#' * level} `{attr.name}`", "", "```python", f"{attr.name}{annotation}", "```", ""]
    out += render_docstring(attr, level=level + 1)
    return out


def format_parameters(fn: griffe.Function) -> str:
    """Format parameters with the `/` and `*` markers, dropping `self` and `cls`."""
    params = list(fn.parameters)
    if fn.parent is not None and fn.parent.kind is griffe.Kind.CLASS and params:
        if params[0].name in ("self", "cls"):
            params = params[1:]

    parts: list[str] = []
    kinds = [p.kind for p in params]
    for i, param in enumerate(params):
        if param.kind is griffe.ParameterKind.keyword_only and griffe.ParameterKind.var_positional not in kinds:
            if i == 0 or params[i - 1].kind is not griffe.ParameterKind.keyword_only:
                parts.append("*")
        parts.append(format_parameter(param))
        if param.kind is griffe.ParameterKind.positional_only and (
            i + 1 == len(params) or params[i + 1].kind is not griffe.ParameterKind.positional_only
        ):
            parts.append("/")
    return ", ".join(parts)


def format_parameter(param: griffe.Parameter) -> str:
    kind = param.kind
    name = param.name
    if kind is griffe.ParameterKind.var_positional:
        name = f"*{name}"
    elif kind is griffe.ParameterKind.var_keyword:
        name = f"**{name}"
    text = f"{name}: {param.annotation}" if param.annotation else name
    if param.default is not None:
        text += f" = {param.default}" if param.annotation else f"={param.default}"
    return text


def render_docstring(obj: griffe.Object, level: int) -> list[str]:
    if obj.docstring is None:
        return []
    out: list[str] = []
    for section in obj.docstring.parsed:
        kind = section.kind
        if kind is griffe.DocstringSectionKind.text:
            out += [demote_headings(section.value, level), ""]
        elif kind in (griffe.DocstringSectionKind.parameters, griffe.DocstringSectionKind.other_parameters):
            out += [f"**{section.title or 'Parameters'}**", "", "| Name | Type | Description |", "|---|---|---|"]
            out += [
                f"| `{p.name}` | {code(p.annotation)} | {cell(p.description)} |" for p in section.value
            ]
            out += [""]
        elif kind in (griffe.DocstringSectionKind.returns, griffe.DocstringSectionKind.yields):
            out += [f"**{section.title or kind.value.capitalize()}**", ""]
            out += [f"- {code(r.annotation)} {r.description}".rstrip() for r in section.value]
            out += [""]
        elif kind in (griffe.DocstringSectionKind.raises, griffe.DocstringSectionKind.warns):
            out += [f"**{section.title or kind.value.capitalize()}**", ""]
            out += [f"- {code(r.annotation)}: {r.description}" for r in section.value]
            out += [""]
        elif kind is griffe.DocstringSectionKind.examples:
            out += ["**Examples**", ""]
            for sub_kind, text in section.value:
                is_code = sub_kind is griffe.DocstringSectionKind.examples
                out += (["```pycon", text, "```"] if is_code else [text]) + [""]
        elif kind is griffe.DocstringSectionKind.admonition:
            out += [f":::note[{section.title}]", section.value.description, ":::", ""]
    return out


def demote_headings(text: str, level: int) -> str:
    """Nest Markdown headings from docstrings (e.g. rustdoc `# Errors`) under the item."""
    lines, in_fence = [], False
    for line in text.splitlines():
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
        if not in_fence:
            line = HEADING.sub(lambda m: "#" * min(len(m[1]) + level - 1, 6) + m[2], line)
        lines.append(line)
    return "\n".join(lines)


def code(value: object) -> str:
    return f"`{value}`" if value else ""


def cell(text: str) -> str:
    return text.replace("\n", " ").replace("|", "\\|")


if __name__ == "__main__":
    main()
